In [1]:
import librosa
from librosa import feature, effects, beat
import pandas as pd
import numpy as np
import tensorflow as tf
from pydub import AudioSegment

In [3]:
def get_features(filePath):
    data, sr = librosa.load(filePath)
    
    # Length
    length = data.size
    
    # Chroma_stft
    chroma_stft = feature.chroma_stft(y=data)
    chroma_stft_mean = np.mean(chroma_stft)
    chroma_stft_var = np.var(chroma_stft)
    
    # RMS
    rms = feature.rms(y=data)
    rms_mean = np.mean(rms)
    rms_var = np.var(rms)
    
    # Spectral Centroid
    spectral_centroid = feature.spectral_centroid(y=data)
    spectral_centroid_mean = np.mean(spectral_centroid)
    spectral_centroid_var = np.var(spectral_centroid)
    
    # Spectral Bandwidth
    spectral_bandwidth = feature.spectral_bandwidth(y=data)
    spectral_bandwidth_mean = np.mean(spectral_bandwidth)
    spectral_bandwidth_var = np.var(spectral_bandwidth)
    
    # Rolloff
    spectral_rolloff = feature.spectral_rolloff(y=data)
    spectral_rolloff_mean = np.mean(spectral_rolloff)
    spectral_rolloff_var = np.var(spectral_rolloff)
    
    # Zero Crossing Rate
    zero_crossing_rate = feature.zero_crossing_rate(y=data)
    zero_crossing_rate_mean = np.mean(zero_crossing_rate)
    zero_crossing_rate_var = np.var(zero_crossing_rate)
    
    # Harmony and perceptr
    harmony, perceptr = effects.hpss(data)
    harmony_mean = np.mean(harmony)
    harmony_var = np.var(harmony)
    perceptr_mean = np.mean(perceptr)
    perceptr_var = np.var(perceptr)
    
    # Tempo
    tempo, _ = beat.beat_track(y=data)
    
    # MFCC
    mfcc_20c = feature.mfcc(y=data)
    mfcc = []
    for i in range(len(mfcc_20c)):
        mean = np.mean(mfcc_20c[i])
        var = np.var(mfcc_20c[i])
        mfcc.append(mean)
        mfcc.append(var)
        

    # Combine all features
    features = [
        chroma_stft_mean, chroma_stft_var, rms_mean, rms_var, spectral_centroid_mean, spectral_centroid_var, 
        spectral_bandwidth_mean, spectral_bandwidth_var, spectral_rolloff_mean, spectral_rolloff_var, 
        zero_crossing_rate_mean, zero_crossing_rate_var, harmony_mean, harmony_var, perceptr_mean, perceptr_var, tempo
    ]
    features.extend(mfcc)
    
    return features

In [4]:
features = get_features("./genres_original/blues/blues.00005.wav")

In [7]:
print(features)

[0.30252185, 0.087551296, 0.103452876, 0.0039811623, 1832.0115969793162, 1030483.8309652422, 1729.5808045469614, 201846.07407526343, 3481.4676306917054, 3274386.1962247384, 0.09404153373936582, 0.006233195614802252, 2.1072713e-06, 0.008084326, -2.7619373e-05, 0.0032444787, 69.83741554054055, -177.80176, 7307.4546, 118.20316, 3195.2053, -17.57063, 654.1079, 30.760931, 485.68976, -21.742554, 433.27664, 11.919263, 266.4076, -20.734299, 169.70601, 3.1852882, 133.70335, -8.580818, 172.22575, -0.9328852, 100.121, -11.772245, 76.554756, -2.408764, 78.802635, -9.348446, 80.10772, -9.942636, 47.53443, -3.9021835, 60.0207, -5.574562, 72.57674, -1.8393143, 68.66612, -2.7893167, 42.470524, -3.0478048, 39.803383, -8.109732, 46.282936]


In [8]:
features = np.reshape(features, [1, 57])
features

array([[ 3.02521855e-01,  8.75512958e-02,  1.03452876e-01,
         3.98116233e-03,  1.83201160e+03,  1.03048383e+06,
         1.72958080e+03,  2.01846074e+05,  3.48146763e+03,
         3.27438620e+06,  9.40415337e-02,  6.23319561e-03,
         2.10727126e-06,  8.08432605e-03, -2.76193732e-05,
         3.24447872e-03,  6.98374155e+01, -1.77801758e+02,
         7.30745459e+03,  1.18203163e+02,  3.19520532e+03,
        -1.75706291e+01,  6.54107910e+02,  3.07609310e+01,
         4.85689758e+02, -2.17425537e+01,  4.33276642e+02,
         1.19192629e+01,  2.66407593e+02, -2.07342987e+01,
         1.69706009e+02,  3.18528819e+00,  1.33703354e+02,
        -8.58081818e+00,  1.72225754e+02, -9.32885230e-01,
         1.00121002e+02, -1.17722454e+01,  7.65547562e+01,
        -2.40876389e+00,  7.88026352e+01, -9.34844589e+00,
         8.01077194e+01, -9.94263554e+00,  4.75344315e+01,
        -3.90218353e+00,  6.00206985e+01, -5.57456207e+00,
         7.25767365e+01, -1.83931434e+00,  6.86661224e+0

In [40]:
model = tf.keras.models.load_model("./Music_Genre_Classifier_30/")

In [7]:
# model.predict(features)

In [2]:
from pydub.utils import make_chunks

In [14]:
file_path = "./genres_original/blues/blues.00005.wav"
myAudio = AudioSegment.from_wav(file_path)
chunks = make_chunks(myAudio, 3000)

In [36]:
for i, chunk in enumerate(chunks):
    chunk_name = "chunk.wav"
    print("exporting", chunk_name)
    chunk.export(chunk_name, format="wav")
    break
    
    
# chunk = enumerate(chunks)
# chunk_name = "chunk.wav"
# print("exporting", chunk_name)
# chunk[0].export(chunk_name, format="wav")

exporting chunk.wav


In [37]:
chunk_file = "./chunk.wav"

In [114]:
features = get_features(chunk_file)

In [115]:
features

[66150,
 0.30415234,
 0.08960826,
 0.073900916,
 0.0013302874,
 1148.4514654857155,
 117070.86654881411,
 1481.6406466510534,
 141709.11046567862,
 2284.4243915264424,
 1324711.6495780337,
 0.049447866586538464,
 0.00019916310112857256,
 1.5377908e-06,
 0.004244045,
 -5.367923e-05,
 0.0011306386,
 67.99958881578948,
 -246.07567,
 9109.914,
 162.99628,
 753.80054,
 -7.9002647,
 949.9101,
 33.968647,
 288.1221,
 -18.322994,
 284.3706,
 10.611111,
 90.568115,
 -23.583687,
 81.565506,
 2.864671,
 77.73566,
 -4.6943593,
 91.436295,
 4.0734553,
 68.90182,
 -13.971252,
 22.683132,
 -5.0048175,
 74.18929,
 -10.499554,
 44.592216,
 -3.9164984,
 24.451086,
 -7.191053,
 25.212744,
 -4.9124804,
 38.22102,
 0.809489,
 18.280386,
 -3.503603,
 23.482914,
 -4.3297496,
 32.046883,
 -6.7947254,
 23.276608]

In [108]:
features = np.reshape(features, [1, 58])

In [109]:
features

array([[ 6.61500000e+04,  3.04152340e-01,  8.96082595e-02,
         7.39009157e-02,  1.33028743e-03,  1.14845147e+03,
         1.17070867e+05,  1.48164065e+03,  1.41709110e+05,
         2.28442439e+03,  1.32471165e+06,  4.94478666e-02,
         1.99163101e-04,  1.53779081e-06,  4.24404489e-03,
        -5.36792286e-05,  1.13063864e-03,  6.79995888e+01,
        -2.46075668e+02,  9.10991406e+03,  1.62996277e+02,
         7.53800537e+02, -7.90026474e+00,  9.49910095e+02,
         3.39686470e+01,  2.88122101e+02, -1.83229942e+01,
         2.84370605e+02,  1.06111107e+01,  9.05681152e+01,
        -2.35836868e+01,  8.15655060e+01,  2.86467099e+00,
         7.77356567e+01, -4.69435930e+00,  9.14362946e+01,
         4.07345533e+00,  6.89018173e+01, -1.39712524e+01,
         2.26831322e+01, -5.00481749e+00,  7.41892929e+01,
        -1.04995537e+01,  4.45922165e+01, -3.91649842e+00,
         2.44510860e+01, -7.19105291e+00,  2.52127438e+01,
        -4.91248035e+00,  3.82210197e+01,  8.09489012e-0

In [55]:
preds = model.predict(features)
preds[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [57]:
model.predict_classes(features)

array([9], dtype=int64)

In [52]:
np.amax(preds)

1.0

In [58]:
df = pd.read_csv('./features_3_sec.csv')
df.head()

filename  length  chroma_stft_mean  chroma_stft_var  rms_mean  \
0  blues.00000.0.wav   66149          0.335406         0.091048  0.130405   
1  blues.00000.1.wav   66149          0.343065         0.086147  0.112699   
2  blues.00000.2.wav   66149          0.346815         0.092243  0.132003   
3  blues.00000.3.wav   66149          0.363639         0.086856  0.132565   
4  blues.00000.4.wav   66149          0.335579         0.088129  0.143289   

    rms_var  spectral_centroid_mean  spectral_centroid_var  \
0  0.003521             1773.065032          167541.630869   
1  0.001450             1816.693777           90525.690866   
2  0.004620             1788.539719          111407.437613   
3  0.002448             1655.289045          111952.284517   
4  0.001701             1630.656199           79667.267654   

   spectral_bandwidth_mean  spectral_bandwidth_var  ...  mfcc16_var  \
0              1972.744388           117335.771563  ...   39.687145   
1              2010.051501            65671.875673  ...   64.748276   
2              2084.565132            75124.921716  ...   67.336563   
3              1960.039988            82913.639269  ...   47.739452   
4              1948.503884            60204.020268  ...   30.336359   

   mfcc17_mean  mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  \
0    -3.241280   36.488243     0.722209   38.099152    -5.050335   33.618073   
1    -6.055294   40.677654     0.159015   51.264091    -2.837699   97.030830   
2    -1.768610   28.348579     2.378768   45.717648    -1.938424   53.050835   
3    -3.841155   28.337118     1.218588   34.770935    -3.580352   50.836224   
4     0.664582   45.880913     1.689446   51.363583    -3.392489   26.738789   

   mfcc20_mean  mfcc20_var  label  
0    -0.243027   43.771767  blues  
1     5.784063   59.943081  blues  
2     2.517375   33.105122  blues  
3     3.630866   32.023678  blues  
4     0.536961   29.146694  blues  

[5 rows x 60 columns]

In [59]:
df = df.drop("filename", axis=1)

In [13]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

In [63]:
class_list = df.iloc[:, -1]
convertor = LabelEncoder()
Y = convertor.fit_transform(class_list)
Y

array([0, 0, 0, ..., 9, 9, 9])

In [66]:
dict(enumerate(convertor.classes_))

{0: 'blues',
 1: 'classical',
 2: 'country',
 3: 'disco',
 4: 'hiphop',
 5: 'jazz',
 6: 'metal',
 7: 'pop',
 8: 'reggae',
 9: 'rock'}

In [96]:
df.head()

length  chroma_stft_mean  chroma_stft_var  rms_mean   rms_var  \
0   66149          0.335406         0.091048  0.130405  0.003521   
1   66149          0.343065         0.086147  0.112699  0.001450   
2   66149          0.346815         0.092243  0.132003  0.004620   
3   66149          0.363639         0.086856  0.132565  0.002448   
4   66149          0.335579         0.088129  0.143289  0.001701   

   spectral_centroid_mean  spectral_centroid_var  spectral_bandwidth_mean  \
0             1773.065032          167541.630869              1972.744388   
1             1816.693777           90525.690866              2010.051501   
2             1788.539719          111407.437613              2084.565132   
3             1655.289045          111952.284517              1960.039988   
4             1630.656199           79667.267654              1948.503884   

   spectral_bandwidth_var  rolloff_mean  ...  mfcc16_var  mfcc17_mean  \
0           117335.771563   3714.560359  ...   39.687145    -3.241280   
1            65671.875673   3869.682242  ...   64.748276    -6.055294   
2            75124.921716   3997.639160  ...   67.336563    -1.768610   
3            82913.639269   3568.300218  ...   47.739452    -3.841155   
4            60204.020268   3469.992864  ...   30.336359     0.664582   

   mfcc17_var  mfcc18_mean  mfcc18_var  mfcc19_mean  mfcc19_var  mfcc20_mean  \
0   36.488243     0.722209   38.099152    -5.050335   33.618073    -0.243027   
1   40.677654     0.159015   51.264091    -2.837699   97.030830     5.784063   
2   28.348579     2.378768   45.717648    -1.938424   53.050835     2.517375   
3   28.337118     1.218588   34.770935    -3.580352   50.836224     3.630866   
4   45.880913     1.689446   51.363583    -3.392489   26.738789     0.536961   

   mfcc20_var  label  
0   43.771767  blues  
1   59.943081  blues  
2   33.105122  blues  
3   32.023678  blues  
4   29.146694  blues  

[5 rows x 59 columns]

In [102]:
np.array(df.iloc[:, :-1])[0]

array([ 6.61490000e+04,  3.35406363e-01,  9.10482928e-02,  1.30405024e-01,
        3.52100423e-03,  1.77306503e+03,  1.67541631e+05,  1.97274439e+03,
        1.17335772e+05,  3.71456036e+03,  1.08078989e+06,  8.18509615e-02,
        5.57687240e-04, -7.84848016e-05,  8.35359003e-03, -6.81618330e-05,
        5.53519279e-03,  1.29199219e+02, -1.18627914e+02,  2.44028662e+03,
        1.25083626e+02,  2.60956909e+02, -2.34437237e+01,  3.64081726e+02,
        4.13214836e+01,  1.81694855e+02, -5.97610807e+00,  1.52963135e+02,
        2.01151409e+01,  7.56522980e+01, -1.60454102e+01,  4.02271042e+01,
        1.78551979e+01,  8.43202820e+01, -1.46334343e+01,  8.34372330e+01,
        1.02705269e+01,  9.70013351e+01, -9.70827866e+00,  6.66698914e+01,
        1.01838751e+01,  4.51036110e+01, -4.68161440e+00,  3.41694984e+01,
        8.41743946e+00,  4.82694435e+01, -7.23347664e+00,  4.27709465e+01,
       -2.85360336e+00,  3.96871452e+01, -3.24128032e+00,  3.64882431e+01,
        7.22208977e-01,  

In [112]:
features

array([[ 6.61500000e+04,  3.04152340e-01,  8.96082595e-02,
         7.39009157e-02,  1.33028743e-03,  1.14845147e+03,
         1.17070867e+05,  1.48164065e+03,  1.41709110e+05,
         2.28442439e+03,  1.32471165e+06,  4.94478666e-02,
         1.99163101e-04,  1.53779081e-06,  4.24404489e-03,
        -5.36792286e-05,  1.13063864e-03,  6.79995888e+01,
        -2.46075668e+02,  9.10991406e+03,  1.62996277e+02,
         7.53800537e+02, -7.90026474e+00,  9.49910095e+02,
         3.39686470e+01,  2.88122101e+02, -1.83229942e+01,
         2.84370605e+02,  1.06111107e+01,  9.05681152e+01,
        -2.35836868e+01,  8.15655060e+01,  2.86467099e+00,
         7.77356567e+01, -4.69435930e+00,  9.14362946e+01,
         4.07345533e+00,  6.89018173e+01, -1.39712524e+01,
         2.26831322e+01, -5.00481749e+00,  7.41892929e+01,
        -1.04995537e+01,  4.45922165e+01, -3.91649842e+00,
         2.44510860e+01, -7.19105291e+00,  2.52127438e+01,
        -4.91248035e+00,  3.82210197e+01,  8.09489012e-0

In [69]:
fit = StandardScaler()
X = fit.fit_transform(np.array(df.iloc[:, :-1], dtype=float))
X.shape

(9990, 58)

In [78]:
X[0]

array([ 0.        , -0.48780784,  0.64052047, -0.00662408,  0.2355679 ,
       -0.56682811, -0.57279059, -0.4939833 , -0.00922924, -0.51859012,
       -0.36795231, -0.45406404, -0.5707769 ,  0.168385  , -0.33595446,
        0.29549517, -0.00997459,  0.13100898,  0.25172824, -0.14198751,
        0.69496363, -0.71318496, -0.56103329, -0.03415077,  0.22904165,
       -0.01664507, -0.29237898,  0.08369783,  0.37304378, -0.4233665 ,
       -0.9219196 , -0.88928787,  0.63731806,  0.2076171 , -0.75401836,
        0.2040636 ,  0.22472928,  0.67357662, -0.40969216,  0.07104592,
        0.6938639 , -0.33850305,  0.07076268, -0.64235701,  1.02775024,
       -0.15378764, -0.51579058, -0.265968  , -0.75012151, -0.2991081 ,
        0.16864712, -0.42513736, -0.00342281, -0.37693831, -0.49946359,
       -0.51356204,  0.12841417, -0.29178072])

In [113]:
f = fit.fit_transform(features)
f

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [79]:
x = np.reshape(X[0], [1, 58])

In [80]:
x

array([[ 0.        , -0.48780784,  0.64052047, -0.00662408,  0.2355679 ,
        -0.56682811, -0.57279059, -0.4939833 , -0.00922924, -0.51859012,
        -0.36795231, -0.45406404, -0.5707769 ,  0.168385  , -0.33595446,
         0.29549517, -0.00997459,  0.13100898,  0.25172824, -0.14198751,
         0.69496363, -0.71318496, -0.56103329, -0.03415077,  0.22904165,
        -0.01664507, -0.29237898,  0.08369783,  0.37304378, -0.4233665 ,
        -0.9219196 , -0.88928787,  0.63731806,  0.2076171 , -0.75401836,
         0.2040636 ,  0.22472928,  0.67357662, -0.40969216,  0.07104592,
         0.6938639 , -0.33850305,  0.07076268, -0.64235701,  1.02775024,
        -0.15378764, -0.51579058, -0.265968  , -0.75012151, -0.2991081 ,
         0.16864712, -0.42513736, -0.00342281, -0.37693831, -0.49946359,
        -0.51356204,  0.12841417, -0.29178072]])

In [84]:
pred = model.predict(x)
pred

array([[1.00000000e+00, 2.16240966e-11, 2.05596296e-09, 4.81293517e-17,
        1.48144639e-11, 4.90437465e-12, 2.44012536e-12, 1.21887052e-13,
        1.09824816e-10, 3.06826431e-09]], dtype=float32)

In [85]:
model.predict_classes(x)

array([0], dtype=int64)

In [86]:
np.amax(pred)

1.0

In [106]:
features

[66150,
 0.30415234,
 0.08960826,
 0.073900916,
 0.0013302874,
 1148.4514654857155,
 117070.86654881411,
 1481.6406466510534,
 141709.11046567862,
 2284.4243915264424,
 1324711.6495780337,
 0.049447866586538464,
 0.00019916310112857256,
 1.5377908e-06,
 0.004244045,
 -5.367923e-05,
 0.0011306386,
 67.99958881578948,
 -246.07567,
 9109.914,
 162.99628,
 753.80054,
 -7.9002647,
 949.9101,
 33.968647,
 288.1221,
 -18.322994,
 284.3706,
 10.611111,
 90.568115,
 -23.583687,
 81.565506,
 2.864671,
 77.73566,
 -4.6943593,
 91.436295,
 4.0734553,
 68.90182,
 -13.971252,
 22.683132,
 -5.0048175,
 74.18929,
 -10.499554,
 44.592216,
 -3.9164984,
 24.451086,
 -7.191053,
 25.212744,
 -4.9124804,
 38.22102,
 0.809489,
 18.280386,
 -3.503603,
 23.482914,
 -4.3297496,
 32.046883,
 -6.7947254,
 23.276608]

In [91]:
fit_feat

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [9]:
features

array([[ 3.02521855e-01,  8.75512958e-02,  1.03452876e-01,
         3.98116233e-03,  1.83201160e+03,  1.03048383e+06,
         1.72958080e+03,  2.01846074e+05,  3.48146763e+03,
         3.27438620e+06,  9.40415337e-02,  6.23319561e-03,
         2.10727126e-06,  8.08432605e-03, -2.76193732e-05,
         3.24447872e-03,  6.98374155e+01, -1.77801758e+02,
         7.30745459e+03,  1.18203163e+02,  3.19520532e+03,
        -1.75706291e+01,  6.54107910e+02,  3.07609310e+01,
         4.85689758e+02, -2.17425537e+01,  4.33276642e+02,
         1.19192629e+01,  2.66407593e+02, -2.07342987e+01,
         1.69706009e+02,  3.18528819e+00,  1.33703354e+02,
        -8.58081818e+00,  1.72225754e+02, -9.32885230e-01,
         1.00121002e+02, -1.17722454e+01,  7.65547562e+01,
        -2.40876389e+00,  7.88026352e+01, -9.34844589e+00,
         8.01077194e+01, -9.94263554e+00,  4.75344315e+01,
        -3.90218353e+00,  6.00206985e+01, -5.57456207e+00,
         7.25767365e+01, -1.83931434e+00,  6.86661224e+0

In [10]:
X_feat = np.array(features)

In [17]:
fit = StandardScaler()
X_trans = fit.fit_transform(X_feat[:, np.newaxis])

ValueError: Found array with dim 3. StandardScaler expected <= 2.

In [16]:
X_trans

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [125]:
X_trans = X_trans.T

In [126]:
X_trans

array([[ 0.21569457, -0.16564838, -0.16564962, -0.16564971, -0.16565013,
        -0.15902948,  0.50924563, -0.1571087 ,  0.65128137, -0.15248077,
         7.47111133, -0.16564985, -0.16565013, -0.16565013, -0.16565011,
        -0.16565013, -0.16565013, -0.16525813, -0.16706872, -0.11313286,
        -0.16471048, -0.16130459, -0.16569568, -0.16017405, -0.16545431,
        -0.16398915, -0.16575576, -0.16401078, -0.16558896, -0.16512802,
        -0.16578609, -0.16517992, -0.16563362, -0.165202  , -0.16567719,
        -0.16512302, -0.16562665, -0.16525292, -0.16573067, -0.16551937,
        -0.16567898, -0.16522244, -0.16571066, -0.16539307, -0.16567271,
        -0.16550918, -0.16569159, -0.16550479, -0.16567845, -0.16542979,
        -0.16564547, -0.16554475, -0.16567033, -0.16551476, -0.16567509,
        -0.16546539, -0.1656893 , -0.16551595]])

In [128]:
X_pred = model.predict(X_trans)
X_pred

array([[1.48508982e-14, 6.21577063e-13, 7.10339426e-11, 1.47189524e-10,
        1.12422075e-14, 5.35016963e-13, 1.17725122e-12, 1.80348371e-13,
        2.55773080e-06, 9.99997497e-01]], dtype=float32)

In [129]:
model.predict_classes(X_trans)

array([9], dtype=int64)

In [130]:
np.amax(X_pred)

0.9999975

In [134]:
dfr1 = np.array(df.iloc[1, :-1])
dfr1

array([66149, 0.3430653512477875, 0.0861465260386467, 0.1126992478966713,
       0.0014496854273602, 1816.6937765281948, 90525.69086581325,
       2010.0515008132973, 65671.87567304078, 3869.6822415865386,
       672244.7602729121, 0.0871732271634615, 0.0010296204950682,
       -9.894942195387556e-05, 0.004950363188982, -0.0001033452499541,
       0.0048535047098994, 123.046875, -125.59070587158205,
       2038.34423828125, 122.42122650146484, 216.7741851806641,
       -20.718019485473636, 231.97976684570312, 50.12838745117188,
       142.70040893554688, -11.33330249786377, 139.2431182861328,
       21.385400772094727, 77.81794738769531, -15.960796356201172,
       97.36402893066406, 19.454103469848636, 57.94809341430664,
       -12.465917587280272, 68.27152252197266, 17.898168563842773,
       56.22217559814453, -11.73255443572998, 54.37390899658203,
       8.145000457763672, 40.66287612915039, -7.717750549316406,
       30.808521270751957, 8.397150039672852, 48.78422546386719,
      

In [135]:
dfr1_trans = fit.fit_transform(dfr1[:, np.newaxis])

In [139]:
dfr1_trans = dfr1_trans.T

In [140]:
dfr1_trans

array([[ 0.5706672 , -0.17644951, -0.17645241, -0.17645211, -0.17645337,
        -0.15593472,  0.84598999, -0.15375084,  0.56527831, -0.13274722,
         7.41622215, -0.1764524 , -0.17645337, -0.17645338, -0.17645333,
        -0.17645338, -0.17645333, -0.17506363, -0.17787187, -0.15343128,
        -0.1750707 , -0.17400502, -0.17668738, -0.17383328, -0.17588721,
        -0.17484165, -0.17658139, -0.1748807 , -0.17621185, -0.17557447,
        -0.17663365, -0.1753537 , -0.17623366, -0.17579889, -0.17659418,
        -0.17568229, -0.17625123, -0.17581838, -0.1765859 , -0.17583926,
        -0.17636139, -0.17599412, -0.17654055, -0.17610542, -0.17635854,
        -0.17590239, -0.17654713, -0.17567875, -0.17640736, -0.17572208,
        -0.17652177, -0.17599395, -0.17645159, -0.17587438, -0.17648543,
        -0.17535747, -0.17638805, -0.17577636]])

In [142]:
dfr_pred = model.predict(dfr1_trans)
dfr_pred

array([[2.2795322e-16, 8.7226250e-15, 3.9767300e-13, 4.0129223e-13,
        3.7173609e-17, 4.3043953e-15, 1.7679639e-14, 9.5602481e-16,
        1.9303147e-10, 1.0000000e+00]], dtype=float32)

In [144]:
model.predict_classes(dfr1_trans)

array([9], dtype=int64)